name: sliding_tile_puzzle
registered_version: SlidingTilePuzzle-v0

network:
    num_channels: 32
    policy_layers: [128, 128]
    value_layers: [256, 256]

training:
    num_epochs: 100
    num_learner_steps_per_epoch: 600
    n_steps: 50
    total_batch_size: 32

evaluation:
    eval_total_batch_size: 500
    greedy_eval_total_batch_size: 500

a2c:
    normalize_advantage: False
    discount_factor: 0.99
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 2e-4
