site_name: Jumanji
site_description: Documentation
site_author: InstaDeep Research
site_url: https://instadeepai.github.io/jumanji/
site_dir: public
strict: false # TODO: Don't allow warning during the build process.

# Copyright
copyright: InstaDeep Â© 2022 Copyright, all rights reserved.

# Git repo
repo_name: instadeepai/jumanji
repo_url: https://github.com/instadeepai/jumanji
edit_uri: edit/develop/docs/

# Navigation Map
nav:
  - Home: index.md
  - Environments:
      - Logic:
          - Game2048: environments/game_2048.md
          - GraphColoring: environments/graph_coloring.md
          - Minesweeper: environments/minesweeper.md
          - RubiksCube: environments/rubiks_cube.md
          - SlidingTilePuzzle: environments/sliding_tile_puzzle.md
          - Sudoku: environments/sudoku.md
      - Packing:
          - BinPack: environments/bin_pack.md
          - FlatPack: environments/flat_pack.md
          - JobShop: environments/job_shop.md
          - Knapsack: environments/knapsack.md
          - Tetris: environments/tetris.md
      - Routing:
          - Cleaner: environments/cleaner.md
          - Connector: environments/connector.md
          - CVRP: environments/cvrp.md
          - Maze: environments/maze.md
          - MMST: environments/mmst.md
          - MultiCVRP: environments/multi_cvrp.md
          - PacMan: environments/pac_man.md
          - RobotWarehouse: environments/robot_warehouse.md
          - Level-Based Foraging: environments/lbf.md
          - Sokoban: environments/sokoban.md
          - Snake: environments/snake.md
          - TSP: environments/tsp.md
      - Swarms:
          - SearchAndRescue: environments/search_and_rescue.md
  - User Guides:
      - Advanced Usage: guides/advanced_usage.md
      - Registration: guides/registration.md
      - Training: guides/training.md
      - Wrapper: guides/wrappers.md
  - API Reference:
      - Environments:
          - Base: api/env.md
          - Logic:
              - Game2048: api/environments/game_2048.md
              - GraphColoring: api/environments/graph_coloring.md
              - Minesweeper: api/environments/minesweeper.md
              - RubiksCube: api/environments/rubiks_cube.md
              - SlidingTilePuzzle: api/environments/sliding_tile_puzzle.md
              - Sudoku: api/environments/sudoku.md
          - Packing:
              - BinPack: api/environments/bin_pack.md
              - FlatPack: api/environments/flat_pack.md
              - JobShop: api/environments/job_shop.md
              - Knapsack: api/environments/knapsack.md
              - Tetris: api/environments/tetris.md
          - Routing:
              - Cleaner: api/environments/cleaner.md
              - Connector: api/environments/connector.md
              - CVRP: api/environments/cvrp.md
              - Maze: api/environments/maze.md
              - MMST: api/environments/mmst.md
              - MultiCVRP: api/environments/multi_cvrp.md
              - PacMan: api/environments/pac_man.md
              - RobotWarehouse: api/environments/robot_warehouse.md
              - Level-Based Foraging: api/environments/lbf.md
              - Sokoban: api/environments/sokoban.md
              - Snake: api/environments/snake.md
              - TSP: api/environments/tsp.md
          - Swarms:
              - SearchAndRescue: api/environments/search_and_rescue.md
          - Wrappers: api/wrappers.md
          - Types: api/types.md

# Configuration
theme:
  name: material
  logo: img/instadeep_logo.png
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: img/instadeep_logo.png
  features:
    - navigation.tracking # the URL is automatically updated with the active anchor
    - navigation.sections # top-level sections are rendered as groups in the sidebar
    - navigation.tabs # horizontal tabs at the top of the page
    - navigation.tabs.sticky # navigation tabs will lock below the header and always remain visible when scrolling
    - navigation.indexes # documents can be directly attached to sections
    - search.highlight # highlight search result
    - search.share # share button
    - search.suggest # smart suggestion
    - toc.integrate
    - toc.follow
    - content.code.annotate
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.gemoji
  - pymdownx.snippets:
      base_path: ./
  - pymdownx.pathconverter:
      base_path: ./
      relative_path: docs
  - toc:
      permalink: "#"
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

plugins:
  - search
  - autorefs
  - git-revision-date
  - include-markdown
  - mknotebooks: # enable Jupyter notebooks
      enable_default_jupyter_cell_styling: false
  - mermaid2 # Class diagrams, flowcharts and more
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            merge_init_into_class: yes
            show_submodules: no
          selection:
            inherited_members: false
          rendering:
            show_source: false
            members_order: source
            show_if_no_docstring: true
            show_signature: true
            show_signature_annotations: true
            show_root_full_path: false
            show_root_heading: true
            merge_init_into_class: true
            docstring_section_style: spacy

# Customization
extra_css:
  - _static/custom.css
